CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password varchar(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    age VARCHAR(255) DEFAULT NULL,
    gender VARCHAR(255) DEFAULT NULL,
    balance NUMERIC(100,2)  DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);
ALTER TABLE public.users ADD CONSTRAINT users_email_unique UNIQUE (email);
