CREATE TABLE ORDERS (
    id SERIAL PRIMARY KEY,
    user_id INT8 NOT NULL,
    event_id INT8 NOT NULL,
    "status" VARCHAR(255) NOT NULL,
    ticket_options JSONB DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);
-- ALTER TABLE orders ADD CONSTRAINT users_email_unique UNIQUE (email);
